import { Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import React, { useState } from 'react'
import { heightPercentageToDP, widthPercentageToDP } from 'react-native-responsive-screen'
import { Router, useRouter } from 'expo-router'
import AntDesign from '@expo/vector-icons/AntDesign';
import { Colors } from '@/constants/Colors';
import { Components } from '@/components';
import ProfileSuccessModal from '@/components/ProfileSuccessModal';

const EditProfile = () => {
    const router: Router = useRouter();
    const [successModalVisible, setSuccessModalVisible] = useState(false);
    const [name, setName] = useState('Leslie Lim Ah Kao');
    const [email, setEmail] = useState('');
    const [phone, setPhone] = useState('');
    const [dob, setDob] = useState('');
    const [userId, setUserId] = useState('');
    return (
        <>
            <View style={styles.topContainer} >
                <View style={styles.topSubContainer} >
                    <AntDesign onPress={() => router.push({ 'pathname': '/(tabs)/profile' })} name="left" size={24} color="black" />
                    <Text style={styles.headerText}>Edit Profile</Text>
                    <AntDesign style={{ opacity: 0 }} onPress={() => router.push({ 'pathname': '/(tabs)/' })} name="left" size={24} color="black" />
                </View>
            </View>

            <ScrollView style={{ paddingTop: heightPercentageToDP(2) }} >
                <View style={{ paddingHorizontal: widthPercentageToDP(5) }}>

                    <View style={styles.flexContainer} >
                        <Text style={styles.headerText}>Account Details</Text>
                    </View>
                    <View style={{ gap: heightPercentageToDP(3), marginTop: heightPercentageToDP(2) }} >
                        <Components.Input value={userId} setValue={setUserId} subTitle='This is generated by the system.' title="User ID" placeholder="leslielimahkao" />
                        <Components.Input value={email} setValue={setEmail} subTitle='Your email address cannot be changed.' title="Email" placeholder="leslielimahkao@jupiter.com" />
                        <Components.Input value={name} setValue={setName} title="Full Name" placeholder="Leslie Lim Ah Kao" />
                        <Components.Input value={phone} setValue={setPhone} title="Phone number" placeholder="9144 4178" />
                        <Components.Input value={dob} setValue={setDob} isCalendar title="Date of birth" placeholder="" />
                    </View>
                </View>
            </ScrollView>
            
            <View style={{ bottom: heightPercentageToDP(5), position: 'absolute', width: '90%', left: '5%' }} >
                <Components.Button onPress={() => setSuccessModalVisible(true)} title='CONFIRM CHANGES' />
            </View>

            <ProfileSuccessModal modalVisible={successModalVisible} setModalVisible={setSuccessModalVisible} />
        </>
    )
}

export default EditProfile

const styles = StyleSheet.create({
    topContainer: {
        height: heightPercentageToDP(10),
        justifyContent: 'flex-end',
        backgroundColor: Colors.white,
        paddingBottom: 10
    },
    topSubContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: widthPercentageToDP(5)
    },
    headerText: {
        fontSize: widthPercentageToDP(4.5),
        fontWeight: 'bold'
    },
    flexContainer: { flexDirection: "row", gap: 5, alignItems: 'center', justifyContent: 'space-between' },

})